/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rolandomagico_processinformation_ProcessInformation */

#ifndef _Included_rolandomagico_processinformation_ProcessInformation
#define _Included_rolandomagico_processinformation_ProcessInformation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rolandomagico_processinformation_ProcessInformation
 * Method:    getCurrentProcessId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_rolandomagico_processinformation_ProcessInformation_getCurrentProcessId
  (JNIEnv *, jclass);

/*
 * Class:     rolandomagico_processinformation_ProcessInformation
 * Method:    getAllProcesses
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_rolandomagico_processinformation_ProcessInformation_getAllProcesses
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
